"""
saturate_insights.py

Refactored script for the saturate-insights skill.
Reads a pre-existing temp_insights.json generated by the Built-in AI Agent,
validates it, and deterministically generates all output Markdown files and charts.

Usage:
    python3 saturate_insights.py <folder_path>
"""

import os
import sys
import json
import re
import argparse

try:
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    MATPLOTLIB_AVAILABLE = True
except ImportError:
    MATPLOTLIB_AVAILABLE = False

# ============================================================================
# SECTION 1: JSON Loading & Validation
# ============================================================================

def load_insights(folder_path):
    """
    Read and parse temp_insights.json from the given folder.

    Returns:
        dict: The parsed JSON data.

    Raises:
        FileNotFoundError: If temp_insights.json does not exist.
        ValueError: If the file contains invalid JSON.
    """
    json_path = os.path.join(folder_path, "temp_insights.json")
    if not os.path.exists(json_path):
        raise FileNotFoundError(
            f"temp_insights.json not found in {folder_path}. "
            "Please ensure the AI agent has generated it before running this script."
        )

    with open(json_path, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON in temp_insights.json: {e}")

    return data


def validate_schema(data):
    """
    Validate that the JSON data conforms to the expected schema.

    Raises:
        ValueError: If validation fails.
    """
    if not isinstance(data, dict):
        raise ValueError("Root element must be a JSON object.")

    if "interviewees" not in data:
        raise ValueError("Missing required field: 'interviewees'.")
    if not isinstance(data["interviewees"], list) or len(data["interviewees"]) == 0:
        raise ValueError("'interviewees' must be a non-empty list.")

    if "master_insights" not in data:
        raise ValueError("Missing required field: 'master_insights'.")
    if not isinstance(data["master_insights"], list):
        raise ValueError("'master_insights' must be a list.")

    valid_statuses = {"new", "repeated", "absent"}

    for i, insight in enumerate(data["master_insights"]):
        prefix = f"master_insights[{i}]"

        if "id" not in insight:
            raise ValueError(f"{prefix}: Missing required field 'id'.")
        if "insight" not in insight:
            raise ValueError(f"{prefix}: Missing required field 'insight'.")
        if "interviewees" not in insight:
            raise ValueError(f"{prefix}: Missing required field 'interviewees'.")
        if not isinstance(insight["interviewees"], dict):
            raise ValueError(f"{prefix}.interviewees must be a dict.")

        for name, entry in insight["interviewees"].items():
            entry_prefix = f"{prefix}.interviewees['{name}']"
            if "status" not in entry:
                raise ValueError(
                    f"{entry_prefix}: Missing required field 'status'."
                )
            if entry["status"] not in valid_statuses:
                raise ValueError(
                    f"{entry_prefix}: Invalid status '{entry['status']}'. "
                    f"Must be one of: {valid_statuses}."
                )
            if "quotes" not in entry:
                raise ValueError(
                    f"{entry_prefix}: Missing required field 'quotes'."
                )
            if not isinstance(entry["quotes"], list):
                raise ValueError(f"{entry_prefix}.quotes must be a list.")


# ============================================================================
# SECTION 2: Report Generation
# ============================================================================

def _sanitize_filename(name):
    """
    Convert an interviewee alias to a safe filename component.
    Replaces spaces and special characters with underscores.
    """
    safe = re.sub(r"[^\w\-]", "_", name, flags=re.UNICODE)
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe


def _escape_pipe(text):
    """Escape pipe characters in text for Markdown table cells."""
    return text.replace("|", "\\|")


def generate_individual_report(interviewee, insights_data):
    """
    Generate the content for an all-insights-<interviewee>.md file.

    Args:
        interviewee: The interviewee alias string.
        insights_data: The full parsed JSON data dict.

    Returns:
        str: The Markdown content for the individual report.
    """
    lines = []
    lines.append(f"# Insights — {interviewee}\n")
    lines.append("")
    lines.append("| # | Insight | Quotes |")
    lines.append("|---|---------|--------|")

    row_num = 0
    for insight in insights_data["master_insights"]:
        entry = insight["interviewees"].get(interviewee)
        if not entry or entry["status"] == "absent":
            continue

        row_num += 1
        insight_text = _escape_pipe(insight["insight"])
        quotes = entry.get("quotes", [])
        if quotes:
            quotes_text = "<br><br>".join(
                _escape_pipe(q) for q in quotes
            )
        else:
            quotes_text = "—"

        lines.append(f"| {row_num} | {insight_text} | {quotes_text} |")

    lines.append("")
    return "\n".join(lines)


def generate_combined_report(insights_data, folder_path):
    """
    Generate insights.md by compiling all individual interviewee reports.

    Returns:
        str: Path to the generated insights.md file.
    """
    lines = []
    lines.append("# Compiled Insights\n")

    # --- Summary Section ---
    lines.append("## Summary of Master Insights\n")
    for insight in insights_data["master_insights"]:
        insight_text = _escape_pipe(insight["insight"])
        theme = insight.get("theme")
        if not theme:
            # Fallback theme if not specified in JSON
            first_part = insight_text.split(",")[0]
            words = first_part.split()
            theme = " ".join(words[:3]) if len(words) >= 3 else first_part
        lines.append(f"- **{theme}**: {insight_text}")
    lines.append("\n---\n")

    for interviewee in insights_data["interviewees"]:
        individual_content = generate_individual_report(
            interviewee, insights_data
        )
        lines.append(individual_content)
        lines.append("---\n")

    if lines and lines[-1] == "---\n":
        lines.pop()

    output_path = os.path.join(folder_path, "insights.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output_path


def generate_all_individual_reports(insights_data, folder_path):
    """
    Generate all-insights-<interviewee>.md files for each interviewee.

    Returns:
        list[str]: Paths to all generated files.
    """
    output_files = []

    for interviewee in insights_data["interviewees"]:
        content = generate_individual_report(interviewee, insights_data)
        safe_name = _sanitize_filename(interviewee)
        filename = f"all-insights-{safe_name}.md"
        output_path = os.path.join(folder_path, filename)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        output_files.append(output_path)

    return output_files


def generate_saturation_matrix(insights_data, folder_path):
    """
    Generate saturation-matrix.md containing:
    1. A data saturation matrix table (🔵 new, 🌐 repeated, ⚪️ absent)
    2. A summary row with cumulative new insight counts
    3. A matplotlib-generated PNG data saturation chart

    Returns:
        tuple: (Path to saturation-matrix.md, Path to saturation-chart.png)
    """
    interviewees = insights_data["interviewees"]
    master_insights = insights_data["master_insights"]

    status_symbols = {
        "new": "🔵",
        "repeated": "🌐",
        "absent": "⚪️",
    }

    lines = []
    lines.append("# Data Saturation Matrix\n")
    lines.append("")

    # --- Table Header ---
    header_cols = ["Insight"] + interviewees
    lines.append("| " + " | ".join(header_cols) + " |")
    lines.append("| " + " | ".join(["---"] * len(header_cols)) + " |")

    # --- Table Body ---
    new_counts = {name: 0 for name in interviewees}

    for insight in master_insights:
        row = [_escape_pipe(insight["insight"])]
        for name in interviewees:
            entry = insight["interviewees"].get(name)
            if entry:
                status = entry["status"]
                symbol = status_symbols.get(status, "⚪️")
                if status == "new":
                    new_counts[name] += 1
            else:
                symbol = "⚪️"
            row.append(symbol)
        lines.append("| " + " | ".join(row) + " |")

    # --- Summary Row ---
    summary_row = ["**🔵 New Insights**"]
    for name in interviewees:
        summary_row.append(str(new_counts[name]))
    lines.append("| " + " | ".join(summary_row) + " |")

    lines.append("")

    # --- Data Saturation Chart (Matplotlib PNG) ---
    chart_path = os.path.join(folder_path, "saturation-chart.png")
    
    if MATPLOTLIB_AVAILABLE:
        # Sort interviewees by new insight count (descending) for the chart
        sorted_pairs = sorted([(name, new_counts[name]) for name in interviewees], key=lambda x: x[1], reverse=True)
        sorted_interviewees = [pair[0] for pair in sorted_pairs]
        sorted_y = [pair[1] for pair in sorted_pairs]
        
        plt.figure(figsize=(10, 6))
        
        # Plot drastic downward slope line
        plt.plot(sorted_interviewees, sorted_y, marker='o', linestyle='-', color='#2b8a3e', linewidth=3, markersize=8)
        
        # Translucent green area fill
        plt.fill_between(sorted_interviewees, sorted_y, color='#40c057', alpha=0.3)
        
        plt.title('Data Saturation Curve (Marginal New Insights)', fontsize=16, fontweight='bold', pad=20)
        plt.xlabel('Interview Sequence', fontsize=12, labelpad=10)
        plt.ylabel('New Findings Discovered', fontsize=12, labelpad=10)
        
        # Clean, uncluttered axes
        plt.gca().yaxis.set_major_locator(ticker.MaxNLocator(integer=True))
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.gca().spines['top'].set_visible(False)
        plt.gca().spines['right'].set_visible(False)
        
        plt.tight_layout()
        plt.savefig(chart_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        lines.append("## Data Saturation Chart\n")
        lines.append("")
        lines.append("![Data Saturation Curve](saturation-chart.png)")
        lines.append("")
    else:
        # Fallback if matplotlib is missing
        lines.append("## Data Saturation Chart\n")
        lines.append("*(Matplotlib is required to generate the chart. Install with `pip install matplotlib`)*")
        lines.append("")

    output_path = os.path.join(folder_path, "saturation-matrix.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output_path, chart_path


def merge_final_report(combined_path, matrix_path):
    """
    Appends the contents of saturation-matrix.md into insights.md,
    then deletes saturation-matrix.md.
    """
    with open(matrix_path, "r", encoding="utf-8") as f:
        matrix_content = f.read()
    
    with open(combined_path, "a", encoding="utf-8") as f:
        f.write("\n\n---\n\n")
        f.write(matrix_content)
        
    os.remove(matrix_path)


# ============================================================================
# SECTION 3: Main CLI Entry Point
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Saturate Insights: Generate insight reports from temp_insights.json."
    )
    parser.add_argument(
        "folder_path",
        help="Path to the folder containing temp_insights.json."
    )

    args, _ = parser.parse_known_args()
    folder_path = args.folder_path

    # Validate folder
    if not os.path.isdir(folder_path):
        print(json.dumps({
            "status": "error",
            "error_code": "INVALID_INPUT",
            "message": f"Folder not found: {folder_path}"
        }))
        sys.exit(1)

    interview_dir = os.path.join(folder_path, "Interview")
    if not os.path.exists(interview_dir):
        print(json.dumps({
            "status": "error",
            "error_code": "INVALID_INPUT",
            "message": f"Interview folder not found: {interview_dir}"
        }))
        sys.exit(1)

    json_path = os.path.join(interview_dir, "temp_insights.json")

    # --- Phase 1: Load & Validate ---
    try:
        data = load_insights(interview_dir)
    except FileNotFoundError as e:
        print(json.dumps({
            "status": "error",
            "error_code": "NO_INSIGHTS_JSON",
            "message": str(e)
        }))
        sys.exit(1)
    except ValueError as e:
        print(json.dumps({
            "status": "error",
            "error_code": "INVALID_JSON",
            "message": str(e)
        }))
        sys.exit(1)

    try:
        validate_schema(data)
    except ValueError as e:
        print(json.dumps({
            "status": "error",
            "error_code": "SCHEMA_VALIDATION_ERROR",
            "message": str(e)
        }))
        sys.exit(1)

    # --- Phase 2: Generate outputs ---
    try:
        individual_files = generate_all_individual_reports(data, interview_dir)
        combined_path = generate_combined_report(data, interview_dir)
        matrix_path, chart_path = generate_saturation_matrix(data, interview_dir)
        merge_final_report(combined_path, matrix_path)
    except Exception as e:
        print(json.dumps({
            "status": "error",
            "error_code": "GENERATION_ERROR",
            "message": f"Failed to generate output files: {str(e)}"
        }))
        sys.exit(1)

    # --- Phase 3: Cleanup ---
    if os.path.exists(json_path):
        os.remove(json_path)

    all_output_files = individual_files + [combined_path]
    if MATPLOTLIB_AVAILABLE:
        all_output_files.append(chart_path)

    print(json.dumps({
        "status": "success",
        "output_files": [os.path.basename(f) for f in all_output_files]
    }))


if __name__ == "__main__":
    main()
